name: toolbox
description: A library that contains the required tools .
version: 0.0.1
homepage: https://github.com/shervin-h/toolbox
repository: https://github.com/shervin-h/toolbox
issue_tracker: https://github.com/shervin-h/toolbox/issues

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  location: ^5.0.3
  shamsi_date: ^1.0.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
